<?php

    //THIS PHP FILE WILL BE FOR VOLUNTEERS TO VIEW OTHER VOLUNTEERS PROFILES FROM THE SAME GROUPS
    //CAN ONLY SEE THE TOTAL HOURS EARNED, THEIR MILESTONES, ANY VOLUNTEER OF THE MONTHS, AND THEIR GROUPS



    



