<?php

include_once('dbinfo.php');
include_once(dirname(__FILE__).'/../domain/PalletEvent.php');
include_once(dirname(__FILE__).'/../database/dbPalletCounts.php');

//Added to send emails to users when they are removed or signed up to an event.
//include_once(dirname(__FILE__).'/../email.php');

/*
 * add a pallet to dbpalletevent table: return id generated by sql autoincrement
 */

function add_palletEvent($name, $personId) {

    $con=connect();
    mysqli_query($con,'INSERT INTO dbpalletevent (name, personId, date) VALUES("' .
            $name . '","' .
            $personId . '","' .
            date('Y-m-d') . '");');							
    $id = mysqli_insert_id($con);
    mysqli_close($con);
    
    return $id;
}

/*
 * remove a pallet from dbpalletevent table.  If already there, return false
 */

function remove_palletEvent($id) {
    $con=connect();
    $query = 'SELECT * FROM dbpalletevent WHERE id = "' . $id . '"';
    $result = mysqli_query($con,$query);
    if ($result == null || mysqli_num_rows($result) == 0) {
        mysqli_close($con);
        return false;
    }
    $query = 'DELETE FROM dbpalletevent WHERE id = "' . $id . '"';
    $result = mysqli_query($con,$query);

    mysqli_close($con);

    return delete_palletCount_by_palletEvent($id);
}

/*
 * @return an Event from dbEvents table matching a particular id.
 * if not in table, return false
 */

function retrieve_palletEvent($id) {
    $con=connect();
    $query = "SELECT * FROM dbpalletevent WHERE id = '" . $id . "'";
    $result = mysqli_query($con,$query);
    if (mysqli_num_rows($result) !== 1) {
        mysqli_close($con);
        return false;
    }
    $result_row = mysqli_fetch_assoc($result);
    // var_dump($result_row);
    $theEvent = make_an_palletEvent($result_row);
    mysqli_close($con);
    return $theEvent;
}

// not in use, may be useful for future iterations in changing how events are edited (i.e. change the remove and create new event process)
function update_palletEvent_date($id, $new_event_date) {
	$con=connect();
	$query = 'UPDATE dbpalletevent SET date = "' . $new_event_date . '" WHERE id = "' . $id . '"';
	$result = mysqli_query($con,$query);
	mysqli_close($con);
	return $result;
}

function update_palletEvent_name($id, $name) {
    $con=connect();
    $query = 'SELECT * FROM dbpalletevent WHERE id = "' . $id . '"';
    $result = mysqli_query($con,$query);
    if ($result == null || mysqli_num_rows($result) == 0) {
        mysqli_close($con);
        return false;
    }

    $update_query = "UPDATE `dbpalletevent` SET 
       `name` = '$name' 
        where `id` = '$id' ";

    // Perform the insert
    if (mysqli_query($con, $update_query)) {
        mysqli_close($con);
        return true;
    } else {
        mysqli_close($con);
        return false;
    }   
}

function update_palletEvent_notes($id, $notes) {
    $con=connect();
    $query = 'SELECT * FROM dbpalletevent WHERE id = "' . $id . '"';
    $result = mysqli_query($con,$query);
    if ($result == null || mysqli_num_rows($result) == 0) {
        mysqli_close($con);
        return false;
    }

    $update_query = "UPDATE `dbpalletevent` SET 
       `notes` = '" . mysqli_real_escape_string($con, $notes) . "' 
        where `id` = '" . $id . "' ";

    // Perform the update
    if (mysqli_query($con, $update_query)) {
        mysqli_close($con);
        return true;
    } else {
        mysqli_close($con);
        return false;
    }   
}


function make_an_palletEvent($result_row) {
    $theEvent = new PalletEvent(
                    $result_row['id'],
                    $result_row['name'],
                    $result_row['personId'],
                    $result_row['date'],
                    $result_row['notes'] ?? null
                );
    return $theEvent;
}

/*
 * return an array of all the Pallets
 */

function get_all_palletEvents() {
    $con=connect();
    $query = "SELECT * FROM dbpalletevent";
    $result = mysqli_query($con,$query);
    $theEvents = array();
    while ($result_row = mysqli_fetch_assoc($result)) {
        $theEvent = make_an_palletEvent($result_row);
        $theEvents[] = $theEvent;
    }
    mysqli_close($con);
    return $theEvents;
 }

 function pallet_name_unique($name) {
    $con=connect();
    $query = "SELECT * FROM dbpalletevent WHERE name = '" . $name . "'";
    $result = mysqli_query($con,$query);
    if (mysqli_num_rows($result) != 0) {
        mysqli_close($con);
        return false;
    }
    mysqli_close($con);
    return true;
}
