<?php
/*
 * Copyright 2013 by Jerrick Hoang, Ivy Xing, Sam Roberts, James Cook, 
 * Johnny Coster, Judy Yang, Jackson Moniaga, Oliver Radwan, 
 * Maxwell Palmer, Nolan McNair, Taylor Talmage, and Allen Tucker. 
 * This program is part of RMH Homebase, which is free software.  It comes with 
 * absolutely no warranty. You can redistribute and/or modify it under the terms 
 * of the GNU General Public License as published by the Free Software Foundation
 * (see <http://www.gnu.org/licenses/ for more information).
 * 
 */

/**
 * @version March 21, 2026
 * @author Oliver Radwan and Allen Tucker
 */

/* 
 * Created for Gwyneth's Gift in 2022 using original Homebase code as a guide
 */


include_once('dbinfo.php');
include_once(dirname(__FILE__).'/../domain/ShoppingEvent.php');

//Added to send emails to users when they are removed or signed up to an event.
//include_once(dirname(__FILE__).'/../email.php');

/*
 * add an event to dbShoppingEvent table: return id generated by sql autoincrement
 */

function add_shoppingEvent($personId, $familySize, $date) {
    $con=connect();
    mysqli_query($con,'INSERT INTO dbshoppingevent (personId, familySize, date) VALUES("' .
            $personId . '","' . 
            $familySize . '","' . 
            $date . '");');							
    $id = mysqli_insert_id($con);
    mysqli_close($con);
    
    return $id;
}

/*
 * remove an event from dbEvents table.  If already there, return false
 */

function remove_shoppingEvent($id) {
    $con=connect();
    $query = 'SELECT * FROM dbshoppingevent WHERE id = "' . $id . '"';
    $result = mysqli_query($con,$query);
    if ($result == null || mysqli_num_rows($result) == 0) {
        mysqli_close($con);
        return false;
    }
    $query = 'DELETE FROM dbshoppingevent WHERE id = "' . $id . '"';
    $result = mysqli_query($con,$query);

    mysqli_close($con);
    return true;
}


/*
 * @return an Event from dbEvents table matching a particular id.
 * if not in table, return false
 */

function retrieve_shoppingEvent($id) {
    $con=connect();
    $query = "SELECT * FROM dbshoppingevent WHERE id = '" . $id . "'";
    $result = mysqli_query($con,$query);
    if (mysqli_num_rows($result) !== 1) {
        mysqli_close($con);
        return false;
    }
    $result_row = mysqli_fetch_assoc($result);
    $theEvent = make_an_shoppingEvent($result_row);
    mysqli_close($con);
    return $theEvent;
}

// not in use, may be useful for future iterations in changing how events are edited (i.e. change the remove and create new event process)
function update_shoppingEvent_date($id, $new_event_date) {
	$con=connect();
	$query = 'UPDATE dbshoppingevent SET date = "' . $new_event_date . '" WHERE id = "' . $id . '"';
	$result = mysqli_query($con,$query);
	mysqli_close($con);
	return $result;
}

function make_an_shoppingEvent($result_row) {
	/*
	 ($en, $v, $sd, $description, $ev))
	 */
    $theEvent = new ShoppingEvent(
                    $result_row['id'],
                    $result_row['personId'],
                    $result_row['familySize'],
                    $result_row['date']
                );
    return $theEvent;
}

/*
 * return an array of all the Inventory Events
 */

function get_all_shoppingEvents() {
    $con=connect();
    $query = "SELECT * FROM dbshoppingevent";
    $result = mysqli_query($con,$query);
    $theEvents = array();
    while ($result_row = mysqli_fetch_assoc($result)) {
        $theEvent = make_an_shoppingEvent($result_row);
        $theEvents[] = $theEvent;
    }
    mysqli_close($con);
    return $theEvents;
 }

/*
 * return an array of all the Inventory Events with a given date
 * Events are ordered Newest to Oldest
 */

 function get_all_shoppingEvents_by_date($date) {
    $con=connect();
    $query = "SELECT * FROM dbshoppingevent WHERE date = '" . $date . "' ORDER BY id DESC";
    $result = mysqli_query($con,$query);
    $theEvents = array();
    while ($result_row = mysqli_fetch_assoc($result)) {
        $theEvent = make_an_shoppingEvent($result_row);
        $theEvents[] = $theEvent;
    }
    mysqli_close($con);
    return $theEvents;
 }


