<?php
declare(strict_types=1);

namespace Pfpms\Tests\Integration\Station;

use PHPUnit\Framework\TestCase;
use Pfpms\Device\DeviceProof;
use Pfpms\Security\Crypto;
use Pfpms\Sync\Canonical;
use RuntimeException;
use stdClass;

/**
 * The Station's crypto contract (50-design §3.2, §3.3, §3.9, D-28) from the server's side: what the tablet's vault.js
 * and proof.js produce (tests/fixtures/station_crypto.json, generated by tests/js/tools/make-station-crypto-fixture.js
 * with WebCrypto) opens and verifies with the repo's own Crypto, Canonical and DeviceProof. No database: the vectors
 * are fixed published test values.
 */
final class StationCryptoFixtureTest extends TestCase
{
    /** @var array<string, mixed>|null */
    private static ?array $fixture = null;

    /** @return array<string, mixed> the fixture with objects as arrays */
    private static function f(): array
    {
        return self::$fixture ??= json_decode(self::text(), true, 512, JSON_THROW_ON_ERROR);
    }

    private static function text(): string
    {
        return (string) file_get_contents(__DIR__ . '/../../fixtures/station_crypto.json');
    }

    /** The signed item S as decoded objects (stdClass), in the key order of 50-design §3.9 (not sorted). */
    private static function itemValue(): stdClass
    {
        $value = json_decode(self::text(), false, 512, JSON_THROW_ON_ERROR)->item->value;
        self::assertInstanceOf(stdClass::class, $value);
        return $value;
    }

    private static function bin(string $hex): string
    {
        $bytes = hex2bin($hex);
        self::assertIsString($bytes, 'hex ' . $hex);
        return $bytes;
    }

    /** Crypto::unb64urlStrict() that must succeed. */
    private static function strict(string $text, ?int $bytes = null): string
    {
        $decoded = Crypto::unb64urlStrict($text, $bytes);
        self::assertNotNull($decoded, 'strict base64url ' . $text);
        return $decoded;
    }

    private static function itemBytes(): string
    {
        return self::f()['item']['canonical'];
    }

    private static function kRec(): string
    {
        return Crypto::hkdf(self::bin(self::f()['dvk_hex']), 'pfpms/v1/record');
    }

    private static function kek(): string
    {
        $k = self::f()['kek'];
        return hash_pbkdf2('sha256', $k['password'], self::bin($k['salt_hex']), $k['iterations'], 32, true);
    }

    /** Asserts that $open throws RuntimeException (AES-GCM refused the key, IV, AAD or bytes). */
    private function assertRefused(callable $open, string $why): void
    {
        try {
            $open();
        } catch (RuntimeException) {
            $this->addToAssertionCount(1);
            return;
        }
        $this->fail('Crypto::openRaw accepted ' . $why);
    }

    public function testPhpOpensTheTabletRecord(): void
    {
        $s = self::f()['outbox_seal'];
        $this->assertSame('outbox', $s['store']);
        $this->assertSame('item.canonical', $s['plaintext_is']);
        $this->assertSame('pfpms/v1|outbox|' . self::f()['item']['value']['client_uuid'], $s['aad']);
        $this->assertSame($s['key'], self::f()['item']['value']['client_uuid']);
        $this->assertSame(self::bin($s['iv_hex']), self::strict($s['iv'], 12));
        $this->assertSame(self::itemBytes(), Crypto::openRaw(self::kRec(), self::strict($s['iv'], 12), self::strict($s['ct']), $s['aad']));
    }

    public function testPhpVerifiesTheItemMac(): void
    {
        $item = self::f()['item'];
        $grant = self::bin($item['grant_key_hex']);
        $this->assertSame(32, strlen($grant));
        $this->assertTrue(hash_equals(Crypto::hmac($grant, self::itemBytes()), self::strict($item['mac'], 32)));
        $this->assertSame($item['mac'], Crypto::b64url(Crypto::hmac($grant, self::itemBytes())));
        $this->assertSame($item['sha256_hex'], hash('sha256', self::itemBytes()));
        $empty = self::f()['hmac_empty'];
        $this->assertSame($empty['mac'], Crypto::b64url(Crypto::hmac(self::bin($empty['key_hex']), '')));
        $this->assertFalse(hash_equals(Crypto::hmac($grant, self::itemBytes() . ' '), self::strict($item['mac'], 32)), 'one more byte is another mac');
    }

    public function testPhpUnwrapsTheKeyringWithTheFixtureKek(): void
    {
        $k = self::f()['kek'];
        $this->assertSame(1000, $k['iterations']);
        $this->assertSame(self::bin($k['salt_hex']), self::strict($k['salt'], 16));
        $this->assertSame($k['kek_hex'], bin2hex(self::kek()));
        $w = self::f()['keyring_wrap'];
        $this->assertSame("pfpms/v1|keyring|{$w['device_id']}|{$w['user_id']}", $w['aad']);
        $this->assertSame(self::bin($w['iv_hex']), self::strict($w['iv'], 12));
        $dvk = Crypto::openRaw(self::kek(), self::strict($w['iv'], 12), self::strict($w['wrapped_dvk'], 48), $w['aad']);
        $this->assertSame(self::f()['dvk_hex'], bin2hex($dvk));
        $wrong = hash_pbkdf2('sha256', $k['password'] . ' ', self::bin($k['salt_hex']), $k['iterations'], 32, true);
        $this->assertRefused(static fn () => Crypto::openRaw($wrong, self::strict($w['iv'], 12), self::strict($w['wrapped_dvk'], 48), $w['aad']),
            'a KEK from another password');
    }

    public function testTheItemBytesAreCanonical(): void
    {
        $bytes = self::itemBytes();
        $this->assertSame(self::f()['item']['canonical_hex'], bin2hex($bytes));
        $this->assertStringContainsString("\u{2028}", $bytes, 'the item holds a literal U+2028');
        $this->assertTrue(Canonical::isCanonical($bytes));
        $decoded = Canonical::decodeObject($bytes);
        $this->assertNotNull($decoded);
        $this->assertSame($bytes, Canonical::encode($decoded), 'encode(decodeObject()) round-trips');
        $this->assertSame($bytes, Canonical::encode(self::itemValue()), 'the value in §3.9 order encodes to the canonical bytes');
        // Mutated items are not canonical, so a bypassed isCanonical() fails here.
        $unsorted = json_encode(self::itemValue(), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_LINE_TERMINATORS | JSON_THROW_ON_ERROR);
        $this->assertNotSame($bytes, $unsorted);
        foreach ([
            'keys in the §3.9 order' => $unsorted,
            'a space after a colon' => preg_replace('/":/', '": ', $bytes, 1),
            'an escaped line separator' => str_replace("\u{2028}", '\u2028', $bytes),
            'a float' => str_replace('"seq":41', '"seq":41.0', $bytes),
            'a final newline' => $bytes . "\n",
            'a duplicate key' => str_replace('{"client_uuid"', '{"client_uuid":"x","client_uuid"', $bytes),
        ] as $why => $mutated) {
            $this->assertIsString($mutated);
            $this->assertNotSame($bytes, $mutated, $why);
            $this->assertFalse(Canonical::isCanonical($mutated), $why);
        }
    }

    public function testPhpOpensTheVaultUsersRecord(): void
    {
        $v = self::f()['vault_users_seal'];
        $this->assertSame('vault_users', $v['store']);
        $this->assertSame('pfpms/v1|vault_users|' . $v['key'], $v['aad']);
        $this->assertSame(self::bin($v['iv_hex']), self::strict($v['iv'], 12));
        $plaintext = Crypto::openRaw(self::kRec(), self::strict($v['iv'], 12), self::strict($v['ct']), $v['aad']);
        $this->assertSame($v['plaintext'], $plaintext);
        $this->assertTrue(Canonical::isCanonical($plaintext));
    }

    public function testTheSubKeysMatch(): void
    {
        $h = self::f()['hkdf'];
        $dvk = self::bin(self::f()['dvk_hex']);
        $this->assertSame(range(0, 31), array_values((array) unpack('C*', $dvk)), 'the DVK is bytes 00..1f');
        $this->assertSame('', $h['salt_hex']);
        $this->assertSame('pfpms/v1/record', $h['record_info']);
        $this->assertSame('pfpms/v1/pin', $h['pin_info']);
        $this->assertSame($h['record_hex'], bin2hex(Crypto::hkdf($dvk, $h['record_info'])));
        $this->assertSame($h['pin_hex'], bin2hex(Crypto::hkdf($dvk, $h['pin_info'])));
        $this->assertSame('pfpms/v1', self::f()['format']);
    }

    public function testThePinVerifierMatches(): void
    {
        $p = self::f()['pin_verifier'];
        $this->assertSame("pfpms/v1/pin|{$p['user_id']}|{$p['pin']}", $p['message']);
        $kPin = Crypto::hkdf(self::bin(self::f()['dvk_hex']), 'pfpms/v1/pin');
        $this->assertSame($p['verifier'], Crypto::b64url(Crypto::hmac($kPin, $p['message'])));
        $this->assertSame(43, strlen($p['verifier']));
    }

    public function testTheProofVectorsVerifyWithDeviceProof(): void
    {
        $proof = self::f()['proof'];
        $key = self::bin($proof['key_hex']);
        $this->assertSame($key, self::strict($proof['key'], 32));
        $this->assertSame(1790856000000, $proof['ts_ms']);
        foreach (['post', 'get'] as $name) {
            $m = $proof[$name];
            $this->assertSame($m['body_sha256'], hash('sha256', $m['body']), $name);
            $this->assertSame($m['message'], DeviceProof::message($m['method'], $m['endpoint'], $proof['ts_ms'], $m['body_sha256']), $name);
            $this->assertSame($m['mac'], Crypto::b64url(Crypto::hmac($key, $m['message'])), $name);
            $this->assertSame(['ts' => $proof['ts_ms'], 'mac' => $m['mac']], DeviceProof::parse($m['header']), $name);
        }
        $this->assertSame('', $proof['get']['body']);
        $this->assertSame('e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', $proof['get']['body_sha256']);
    }

    public function testStrictBase64urlAgrees(): void
    {
        $lists = self::f()['b64url'];
        $this->assertCount(6, $lists['valid']);
        $this->assertCount(9, $lists['invalid']);
        foreach ($lists['valid'] as $case) {
            $bytes = self::bin($case['hex']);
            $this->assertSame($bytes, Crypto::unb64urlStrict($case['text']), $case['text']);
            $this->assertSame($bytes, Crypto::unb64urlStrict($case['text'], strlen($bytes)), $case['text']);
            $this->assertNull(Crypto::unb64urlStrict($case['text'], strlen($bytes) + 1), $case['text'] . ' with another length');
            $this->assertSame($case['text'], Crypto::b64url($bytes));
        }
        foreach ($lists['invalid'] as $text) {
            $this->assertNull(Crypto::unb64urlStrict($text), json_encode($text, JSON_THROW_ON_ERROR));
        }
    }

    public function testAChangedAadOrMovedRecordIsRefused(): void
    {
        $s = self::f()['outbox_seal'];
        $v = self::f()['vault_users_seal'];
        $w = self::f()['keyring_wrap'];
        $kRec = self::kRec();
        $iv = self::strict($s['iv'], 12);
        $ct = self::strict($s['ct']);
        $tag = $ct;
        $tag[strlen($tag) - 1] = chr(ord($tag[strlen($tag) - 1]) ^ 1);
        $changedIv = $iv;
        $changedIv[0] = chr(ord($changedIv[0]) ^ 1);
        $cases = [
            'another client_uuid in the AAD' => static fn () => Crypto::openRaw($kRec, $iv, $ct, 'pfpms/v1|outbox|123e4567-e89b-42d3-a456-426614174001'),
            'the outbox record under the vault_users AAD' => static fn () => Crypto::openRaw($kRec, $iv, $ct, 'pfpms/v1|vault_users|' . $s['key']),
            'the vault_users record moved into the outbox' => static fn () => Crypto::openRaw($kRec, self::strict($v['iv'], 12), self::strict($v['ct']), $s['aad']),
            'a changed tag' => static fn () => Crypto::openRaw($kRec, $iv, $tag, $s['aad']),
            'a changed IV' => static fn () => Crypto::openRaw($kRec, $changedIv, $ct, $s['aad']),
            'the K_pin key' => static fn () => Crypto::openRaw(Crypto::hkdf(self::bin(self::f()['dvk_hex']), 'pfpms/v1/pin'), $iv, $ct, $s['aad']),
            'the keyring wrap for another user' => static fn () => Crypto::openRaw(self::kek(), self::strict($w['iv'], 12), self::strict($w['wrapped_dvk'], 48),
                "pfpms/v1|keyring|{$w['device_id']}|13"),
            'the keyring wrap for another device' => static fn () => Crypto::openRaw(self::kek(), self::strict($w['iv'], 12), self::strict($w['wrapped_dvk'], 48),
                "pfpms/v1|keyring|8|{$w['user_id']}"),
        ];
        foreach ($cases as $why => $open) {
            $this->assertRefused($open, $why);
        }
        // The unchanged record still opens, so the refusals above are about the change alone.
        $this->assertSame(self::itemBytes(), Crypto::openRaw($kRec, $iv, $ct, $s['aad']));
    }
}
